insert into tbuser(id, name, gender, image,password) values(0, 'torang', 'F', 'http://lorempixel.com/100/100/animals/','123');
insert into tbuser(id, name, gender, image,password) values(1, 'lyka', 'F', 'http://lorempixel.com/100/100/nightlife/','123');
insert into tbuser(id, name, gender, image,password) values(2, 'River Beahan', 'F', 'http://lorempixel.com/100/100/people/','123');
insert into tbuser(id, name, gender, image,password) values(3, 'Bernadette Koelpin', 'F', 'http://lorempixel.com/100/100/city/','123');
insert into tbuser(id, name, gender, image,password) values(4, 'Donnie Aufderhar MD', 'F', 'http://lorempixel.com/100/100/nightlife/','123');
insert into tbuser(id, name, gender, image,password) values(5, 'Mr. Sarina Abernathy', 'F', 'http://lorempixel.com/100/100/cats/','123');
insert into tbuser(id, name, gender, image,password) values(6, 'Carli Collier', 'M', 'http://lorempixel.com/100/100/city/','123');
insert into tbuser(id, name, gender, image,password) values(7, 'Eduardo Homenick', 'M', 'http://lorempixel.com/100/100/cats/','123');
insert into tbuser(id, name, gender, image,password) values(8, 'Rachael Kris', 'M', 'http://lorempixel.com/100/100/animals/','123');
insert into tbuser(id, name, gender, image,password) values(9, 'Mr. Cleo Rogahn', 'M', 'http://lorempixel.com/100/100/technics/','123');
insert into tbuser(id, name, gender, image,password) values(10, 'Sam Konopelski', 'M', 'http://lorempixel.com/100/100/cats/','123');
insert into tbuser(id, name, gender, image,password) values(11, 'Lillie Bartoletti', 'M', 'http://lorempixel.com/100/100/fashion/','123');
insert into tbuser(id, name, gender, image,password) values(12, 'Frances Kub', 'M', 'http://lorempixel.com/100/100/animals/','123');
insert into tbuser(id, name, gender, image,password) values(13, 'Hollis Glover', 'M', 'http://lorempixel.com/100/100/city/','123');
insert into tbuser(id, name, gender, image,password) values(14, 'Cheyenne Emmerich', 'M', 'http://lorempixel.com/100/100/nightlife/','123');
insert into tbuser(id, name, gender, image,password) values(15, 'Maymie Ledner III', 'M', 'http://lorempixel.com/100/100/business/','123');
insert into tbuser(id, name, gender, image,password) values(16, 'Kimberly Barton', 'M', 'http://lorempixel.com/100/100/city/','123');
insert into tbuser(id, name, gender, image,password) values(17, 'Bernard Morissette', 'M', 'http://lorempixel.com/100/100/animals/','123');
insert into tbuser(id, name, gender, image,password) values(18, 'Nathan Dibbert MD', 'M', 'http://lorempixel.com/100/100/technics/','123');
insert into tbuser(id, name, gender, image,password) values(19, 'Ms. Simone Johnson', 'M', 'http://lorempixel.com/100/100/cats/','123');
insert into tbrole(id,role) values(1,'Admin');
insert into tbrole(id,role) values(2,'User');
insert into tbuser_role(user_id,role_id) values (1,1);
insert into tbuser_role(user_id,role_id) values (1,2);
insert into tbuser_role(user_id,role_id) values (2,2);